server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: example-service-a
          uri: lb://service-a
          predicates:
            - Path=/**
        - id: example-service-b
          uri: lb://service-b
          predicates:
            - Path=/**