server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: service-a
          uri: lb://example-service-a
          predicates:
            - Path=/service-a/**
        - id: service-b
          uri: lb://example-service-b
          predicates:
            - Path=/service-b/**